version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "9001:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./project:/var/www/html
    depends_on:
      - php

  php:
    container_name: php
    build:
      context: ./docker/php
    volumes:
      - ./project:/var/www/html